### PR TITLE
Add documentation for the first release

### PR DESCRIPTION
**Pull request by krshrimali**
This PR adds documentation for the first release. Following sections have been added:

1. Description
2. Build Instructions
3. Usage
4. Supported Operators

Ideally, we should have `CONTRIBUTING.md` in future when we are ready to accept contributions. Also expecting a Release candidate soon, so that we can link `Release 0.0.1` (also mentioned in this PR's scope).

Preview the README here: https://github.com/krshrimali/CPU-Capability-Dispatcher/blob/doc-update-0.0.1/README.md

cc: @kshitij12345 @krshrimali

### CODE REVIEW

**Comment by krshrimali** [comment]
Should we also add a note on how and why are we using `cpuinfo`? cc: @kshitij12345

**Comment by kshitij12345** [comment]
> Should we also add a note on how and why are we using cpuinfo? cc: @kshitij12345

Yes that would be nice.

Also it would be nice if you can mention a summary of why is this needed based on https://numpy.org/neps/nep-0038-SIMD-optimizations.html#motivation-and-scope (which provides a very nice detail about why and how)

Thank you very much for looking at it!

**Comment by krshrimali** [comment]
> > Should we also add a note on how and why are we using cpuinfo? cc: @kshitij12345
> 
> Yes that would be nice.
> 
> Also it would be nice if you can mention a summary of why is this needed based on https://numpy.org/neps/nep-0038-SIMD-optimizations.html#motivation-and-scope (which provides a very nice detail about why and how)
> 
> Thank you very much for looking at it!

Thanks for the suggestion and reference, @kshitij12345. I'll take a look tomorrow and update the PR. Will request review again once ready :)

**Comment by kshitij12345** [comment]
No hurry. Take your time. Be sure to read the reference it is short and interesting.

**Comment by kshitij12345** [comment]
@krshrimali do you wish to update this PR?

**Comment by krshrimali** [comment]
@kshitij12345 - Allow me some time, really sorry. Got caught up with lots of things, apologies for the delay.

**Comment by kshitij12345** [comment]
Let's merge it as is? It's better than the current one. Wdyt?

**Pull request merged**
